gpuCheck – SELF
gpuCheck Subroutine
3-Clause BSD with attribution
8 statements
Source File
public subroutine gpuCheck(gpuError_t)
Arguments
Type Intent Optional Attributes Name
integer(kind=kind(hipSuccess)) :: gpuError_t
Called by
Contents
Source Code
gpuCheck
Source Code
                      subroutine gpuCheck(gpuError_t)
                        implicit none
                        integer(kind(hipSuccess)) :: gpuError_t
                        if(gpuError_t /= hipSuccess) then
                          write(*,*) "GPU ERROR: Error code = ",gpuError_t
                          call exit(gpuError_t)
                        endif
                      endsubroutine gpuCheck
Call graph
free_mappedscalar3d calls gpucheck
free_scalar3d calls gpucheck
updatedevice_mesh2d calls gpucheck
setelemtorank_domaindecomposition calls gpucheck
setinteriorfromequation_mappedscalar1d calls gpucheck
updatedevice_scalar3d calls gpucheck
updatehost_vector2d calls gpucheck
updatedevice_tensor3d calls gpucheck
boundaryflux_dgmodel1d calls gpucheck
init_lagrange calls gpucheck
updatehost_scalar2d calls gpucheck
setgradientboundarycondition_dgmodel2d calls gpucheck
setinteriorfromequation_mappedvector2d calls gpucheck
init_scalar2d calls gpucheck
setboundarycondition_dgmodel2d calls gpucheck
setboundarycondition_lineareuler2d calls gpucheck
free_domaindecomposition calls gpucheck
free_mesh2d calls gpucheck
init_scalar3d calls gpucheck
fluxmethod_dgmodel3d calls gpucheck
init_scalar1d calls gpucheck
updatedevice_scalar1d calls gpucheck
updatehost_scalar1d calls gpucheck
free_scalar2d calls gpucheck
fluxmethod_dgmodel2d calls gpucheck
init_mesh3d calls gpucheck
setgradientboundarycondition_dgmodel3d calls gpucheck
free_vector3d calls gpucheck
updatedevice_vector3d calls gpucheck
sourcemethod_dgmodel1d calls gpucheck
free_scalar1d calls gpucheck
updatedevice_tensor2d calls gpucheck
updatedevice_scalar2d calls gpucheck
init_mappedscalar2d calls gpucheck
updatedevice_mesh3d calls gpucheck
free_lagrange calls gpucheck
init_mesh2d calls gpucheck
updatehost_scalar3d calls gpucheck
calculateentropy_dgmodel3d calls gpucheck
sourcemethod_dgmodel3d calls gpucheck
free_tensor2d calls gpucheck
init_tensor3d calls gpucheck
updatehost_vector3d calls gpucheck
boundaryflux_dgmodel2d calls gpucheck
calculateentropy_dgmodel2d calls gpucheck
setinteriorfromequation_mappedscalar2d calls gpucheck
free_mesh3d calls gpucheck
init_mappedscalar3d calls gpucheck
setinteriorfromequation_mappedvector3d calls gpucheck
init_vector2d calls gpucheck
setboundarycondition_lineareuler3d calls gpucheck
sourcemethod_dgmodel2d calls gpucheck
free_mappedscalar2d calls gpucheck
sideexchange_mappedscalar1d calls gpucheck
boundaryflux_dgmodel3d calls gpucheck
free_vector2d calls gpucheck
updatedevice_vector2d calls gpucheck
init_tensor2d calls gpucheck
free_tensor3d calls gpucheck
calculateentropy_dgmodel1d calls gpucheck
setinteriorfromequation_mappedscalar3d calls gpucheck
setboundarycondition_dgmodel3d calls gpucheck
init_vector3d calls gpucheck
updatehost_tensor2d calls gpucheck
updatehost_tensor3d calls gpucheck
fluxmethod_dgmodel1d calls gpucheck
setboundarycondition_dgmodel1d calls gpucheck
setboundarycondition_linearshallowwater2d calls gpucheck
setgradientboundarycondition_dgmodel1d calls gpucheck